In [10]:
# 1.Install NumPy in your Python environment using pip, then create a Python file called insta_likes.py and import numpy as np at the top.

In [24]:
!pip install numpy 


[notice] A new release of pip available: 22.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
import numpy as np

In [ ]:
# 2.Create a NumPy array called followers using np.array() that stores the follower counts for 5 Instagram influencers: [1200, 15000, 67000, 340000, 1250000]. Print the array, its shape, number of dimensions, and data type.

In [26]:
np.array([1200, 15000, 67000, 340000, 1250000])

array([   1200,   15000,   67000,  340000, 1250000])

In [27]:
followers = np.array([1200, 15000, 67000, 340000, 1250000])

In [28]:
followers

array([   1200,   15000,   67000,  340000, 1250000])

In [29]:
followers.ndim

1

In [30]:
followers.shape

(5,)

In [31]:
followers.dtype

dtype('int64')

In [32]:
# 3.Use np.arange() to generate an array of order IDs for 10 consecutive Zomato orders starting from 101. Print the array and its size.

In [33]:
np.arange(101, 111)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [34]:
order_ids = np.arange(101, 111)

In [35]:
order_ids

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [36]:
order_ids.size

10

In [37]:
# 4.Create a 3x3 NumPy array using np.eye() to represent a 'like' identity matrix for a new Spotify playlist feature. Print the matrix and explain what the diagonal values represent in a comment.

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
like_matrix = np.eye(3)

In [40]:
like_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# diagonal values are 1 because each influencer is compared with itseif.
# They represent a "like" or self-connection in the identity matrix.

In [42]:
# 5.Convert a Python list of cricket scores [45, 67, 120, 89, 54] to a NumPy array, then use the .itemsize attribute to print how many bytes each score takes in memory.<br><br><em><strong>Hint:</strong> Use np.array() for conversion and .itemsize for memory size.</em>

In [43]:
scores = [45, 67, 120, 89, 54]

In [44]:
scores_array = np.array(scores)

In [45]:
np.array(scores)

array([ 45,  67, 120,  89,  54])

In [49]:
 scores_array.itemsize

8