In [8]:
import numpy as np

In [9]:
# 1.Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.

In [10]:
np.array([
    [4, 5, 3, 4, 5],
    [5, 4, 4, 3, 5],
    [3, 5, 4, 5, 4],
    [4, 3, 5, 4, 3]
])


array([[4, 5, 3, 4, 5],
       [5, 4, 4, 3, 5],
       [3, 5, 4, 5, 4],
       [4, 3, 5, 4, 3]])

In [11]:
ratings = np.array([
    [4, 5, 3, 4, 5],
    [5, 4, 4, 3, 5],
    [3, 5, 4, 5, 4],
    [4, 3, 5, 4, 3]
])


In [12]:
ratings

array([[4, 5, 3, 4, 5],
       [5, 4, 4, 3, 5],
       [3, 5, 4, 5, 4],
       [4, 3, 5, 4, 3]])

In [13]:
ratings[1:3]

array([[5, 4, 4, 3, 5],
       [3, 5, 4, 5, 4]])

In [14]:
# 2.Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong> Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>

In [15]:
np.array([7500, 8200, 9000, 6500, 10500, 7800, 8500, 9200, 7000, 11000])


array([ 7500,  8200,  9000,  6500, 10500,  7800,  8500,  9200,  7000,
       11000])

In [16]:
steps = np.array([7500, 8200, 9000, 6500, 10500, 7800, 8500, 9200, 7000, 11000])

In [17]:
steps

array([ 7500,  8200,  9000,  6500, 10500,  7800,  8500,  9200,  7000,
       11000])

In [18]:
high_steps = steps[steps > 8000]

In [19]:
high_steps

array([ 8200,  9000, 10500,  8500,  9200, 11000])

In [20]:
# 3.Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.

In [21]:
np.array([180, 195, 165, 210, 175, 190, 220, 185])

array([180, 195, 165, 210, 175, 190, 220, 185])

In [22]:
scores = np.array([180, 195, 165, 210, 175, 190, 220, 185])

In [23]:
scores

array([180, 195, 165, 210, 175, 190, 220, 185])

In [24]:
scores[[1, 4, 6]]

array([195, 175, 220])

In [25]:
selected_scores = scores[[1, 4, 6]]

In [26]:
selected_scores

array([195, 175, 220])

In [27]:
# 4.Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.<br><br><em><strong>Constraint:</strong> Do not use any loops.</em>

In [28]:
np.array([500, 1000, 1500, 2000, 2500])


array([ 500, 1000, 1500, 2000, 2500])

In [29]:
prices = np.array([500, 1000, 1500, 2000, 2500])

In [30]:
prices

array([ 500, 1000, 1500, 2000, 2500])

In [31]:
prices*10/100

array([ 50., 100., 150., 200., 250.])

In [32]:
discounted_prices = prices*10/100

In [33]:
prices-discounted_prices

array([ 450.,  900., 1350., 1800., 2250.])

In [34]:
# 5.Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.

In [35]:
np.array([-2, 5, 0, -1, 4, -3, 2])

array([-2,  5,  0, -1,  4, -3,  2])

In [36]:
ratings = np.array([-2, 5, 0, -1, 4, -3, 2])

In [37]:
ratings

array([-2,  5,  0, -1,  4, -3,  2])

In [38]:
ratings < 0

array([ True, False, False,  True, False,  True, False])

In [39]:
ratings[ratings < 0] = 0

In [40]:
ratings

array([0, 5, 0, 0, 4, 0, 2])