In [2]:
import numpy as np

In [3]:
# 1.Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.

In [8]:
np.array([5000, 7000, 8000, 6000, 9000, 7500, 8500])

array([5000, 7000, 8000, 6000, 9000, 7500, 8500])

In [9]:
np.array([4000, 6500, 7000, 5500, 8000, 7000, 9000])

array([4000, 6500, 7000, 5500, 8000, 7000, 9000])

In [10]:
bhumi = np.array([5000, 7000, 8000, 6000, 9000, 7500, 8500])
nitu = np.array([4000, 6500, 7000, 5500, 8000, 7000, 9000])

In [12]:
bhumi

array([5000, 7000, 8000, 6000, 9000, 7500, 8500])

In [13]:
nitu

array([4000, 6500, 7000, 5500, 8000, 7000, 9000])

In [14]:
bhumi+nitu

array([ 9000, 13500, 15000, 11500, 17000, 14500, 17500])

In [15]:
bhumi-nitu

array([1000,  500, 1000,  500, 1000,  500, -500])

In [16]:
bhumi*nitu

array([20000000, 45500000, 56000000, 33000000, 72000000, 52500000,
       76500000])

In [17]:
bhumi/nitu

array([1.25      , 1.07692308, 1.14285714, 1.09090909, 1.125     ,
       1.07142857, 0.94444444])

In [18]:
# 2.Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.

In [25]:
np.array([[5, 3, 2],
          [4, 5, 1],
          [2, 4, 5]])

array([[5, 3, 2],
       [4, 5, 1],
       [2, 4, 5]])

In [26]:
np.array([[1, 2, 3],
          [2, 1, 2],
          [3, 2, 1]])

array([[1, 2, 3],
       [2, 1, 2],
       [3, 2, 1]])

In [28]:
user_preferences = np.array([[5, 3, 2],[4, 5, 1],[2, 4, 5]])
song_popularity = np.array([[1, 2, 3],[2, 1, 2],[3, 2, 1]])

In [29]:
np.dot(user_preferences, song_popularity)

array([[17, 17, 23],
       [17, 15, 23],
       [25, 18, 19]])

In [30]:
recommendation_dot = np.dot(user_preferences, song_popularity)

In [31]:
recommendation_dot

array([[17, 17, 23],
       [17, 15, 23],
       [25, 18, 19]])

In [32]:
np.matmul(user_preferences, song_popularity)

array([[17, 17, 23],
       [17, 15, 23],
       [25, 18, 19]])

In [33]:
recommendation_matmul = np.matmul(user_preferences, song_popularity)

In [34]:
recommendation_matmul

array([[17, 17, 23],
       [17, 15, 23],
       [25, 18, 19]])

In [35]:
# np.dot() → performs dot product; its behavior can vary for arrays with more than 2 dimensions.
# np.matmul() → specifically performs matrix multiplication.
# Here, both are doing 3×3 matrix multiplication, so the output is identical.

In [36]:
# 3.Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.

In [39]:
np.array([ [10, 20, 30, 40],
           [50, 60, 70, 80],
           [90, 100, 110, 120],
           [130, 140, 150, 160] ])

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [41]:
pixels = np.array([ [10, 20, 30, 40],
                    [50, 60, 70, 80],
                    [90, 100, 110, 120],
                    [130, 140, 150, 160] ])

In [43]:
pixels.T

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [47]:
np.min(pixels)

np.int64(10)

In [48]:
np.median(pixels)

np.float64(85.0)

In [49]:
np.std(pixels)

np.float64(46.09772228646444)

In [50]:
np.var(pixels)

np.float64(2125.0)

In [54]:
# 4.Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em>

In [55]:
np.array([
    [5, 2, 1],
    [2, 4, 2],
    [1, 2, 5]
])

array([[5, 2, 1],
       [2, 4, 2],
       [1, 2, 5]])

In [56]:
ratings = np.array([
    [5, 2, 1],
    [2, 4, 2],
    [1, 2, 5]
])

In [57]:
ratings

array([[5, 2, 1],
       [2, 4, 2],
       [1, 2, 5]])

In [58]:
np.linalg.inv(ratings)

array([[ 0.25 , -0.125,  0.   ],
       [-0.125,  0.375, -0.125],
       [ 0.   , -0.125,  0.25 ]])

In [61]:
inverse = np.linalg.inv(ratings)

In [62]:
inverse

array([[ 0.25 , -0.125,  0.   ],
       [-0.125,  0.375, -0.125],
       [ 0.   , -0.125,  0.25 ]])

In [59]:
np.linalg.det(ratings)

np.float64(63.99999999999998)

In [64]:
determinant = np.linalg.det(ratings)

In [65]:
determinant

np.float64(63.99999999999998)

In [66]:
np.linalg.eig(ratings)

EigResult(eigenvalues=array([8., 4., 2.]), eigenvectors=array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
       [-5.77350269e-01,  1.68947215e-16, -8.16496581e-01],
       [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [67]:
eigenvalues, eigenvectors = np.linalg.eig(ratings)

In [69]:
eigenvalues

array([8., 4., 2.])

In [70]:
eigenvectors

array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
       [-5.77350269e-01,  1.68947215e-16, -8.16496581e-01],
       [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]])

In [71]:
# 5.Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.

In [72]:
np.array([
    [100, 120, 150, 130, 160, 180],
    [90, 110, 140, 125, 155, 170]
])

array([[100, 120, 150, 130, 160, 180],
       [ 90, 110, 140, 125, 155, 170]])

In [76]:
orders = np.array([
    [100, 120, 150, 130, 160, 180],
    [90, 110, 140, 125, 155, 170]
])

In [77]:
orders

array([[100, 120, 150, 130, 160, 180],
       [ 90, 110, 140, 125, 155, 170]])

In [78]:
orders.reshape(3, 4)

array([[100, 120, 150, 130],
       [160, 180,  90, 110],
       [140, 125, 155, 170]])

In [79]:
reshaped = orders.reshape(3, 4)

In [80]:
reshaped

array([[100, 120, 150, 130],
       [160, 180,  90, 110],
       [140, 125, 155, 170]])

In [81]:
reshaped.flatten()

array([100, 120, 150, 130, 160, 180,  90, 110, 140, 125, 155, 170])

In [82]:
flattened = reshaped.flatten()

In [83]:
flattened

array([100, 120, 150, 130, 160, 180,  90, 110, 140, 125, 155, 170])

In [84]:
np.split(flattened, 2)

[array([100, 120, 150, 130, 160, 180]), array([ 90, 110, 140, 125, 155, 170])]

In [85]:
parts = np.split(flattened, 2)

In [86]:
parts

[array([100, 120, 150, 130, 160, 180]), array([ 90, 110, 140, 125, 155, 170])]

In [87]:
np.vstack(parts)

array([[100, 120, 150, 130, 160, 180],
       [ 90, 110, 140, 125, 155, 170]])

In [88]:
stacked = np.vstack(parts)

In [89]:
stacked

array([[100, 120, 150, 130, 160, 180],
       [ 90, 110, 140, 125, 155, 170]])